### ISSUE TITLE
Mistaken use of phantomJs' "injectJs" in main documentation example

### ISSUE THREAD

**Issue by giacecco** [alexscheelmeyer/node-phantom#1]
Hi alexscheelmeyer , I believe you may be mistakenly giving an URL rather than a path to phantomJs' "injectJs" call in your main example in the README.md . Running the example in fact fails loading jQuery, although the URL is valid.

**Comment by alexscheelmeyer** [comment]
Thanks for pointing this out. You are right, it should actually be includeJs instead of injectJs and the example works because jquery is already loaded on the page. I have updated the example.
