### ISSUE TITLE
callback of page.render didn't work

### ISSUE THREAD

**Issue by zhouseahe** [alexscheelmeyer/node-phantom#109]
It worked well when I used page.render(testFilename); 
but when I used 

```
page.render(testFilename,function(err){
        throw new Error('page.render failed ');
});
```

I always got error . what should I do ? 
@alexscheelmeyer  thanks a lot .

**Comment by mikedarke** [comment]
The callback function gets called on success or error. I think you just need to check if the err object is set.

This worked for me...

``` javascript
    page.render(testFilename, function(err) {
        if (err) {
            console.log(err);
            throw new Error('page.render failed ');
        } else {
            console.log('Rendered the page');
        }
    });
```

**Comment by zhouseahe** [comment]
@mikedarke  , oh , thanks a lot  .
