### ISSUE TITLE
Support for page.renderBase64(format)

### ISSUE THREAD

**Issue by ruzz311** [alexscheelmeyer/node-phantom#13]
The API does not bridge the phantomjs page.renderBase64 method.  This method should return a base64 encoded string of the image in the format provided.

For more details see the official docs: https://github.com/ariya/phantomjs/wiki/API-Reference#wiki-webpage-renderBase64.

**Comment by ruzz311** [comment]
I'll try to dig further into the source and submit a pull request if I have time later

**Comment by alexscheelmeyer** [comment]
This is now supported. Enjoy :)
