### ISSUE TITLE
Ability to pass variables through to page.evaluate()

### ISSUE THREAD

**Issue by rehno-lindeque** [alexscheelmeyer/node-phantom#23]
I have a small commit that adds the ability to pass through variables to `page.evaluate(...)` over here:

https://github.com/circuithub/node-phantom/commit/b0989ad90c4550c872b54f4fc0d5f964f0fda613

**Comment by ehartford** [comment]
+1

**Comment by ehartford** [comment]
see this: https://github.com/ariya/phantomjs/commit/0bb8cff7803b70fe60fd761b1b748b5510705ee0

**Comment by alexscheelmeyer** [comment]
Thanks for this! Just committed a version with your changes.

**Comment by jney** [comment]
what the signature of the function ?
if we follow what's done in phantom it would be :  `page.evaluate(fn, [var1, var2, ..., varn], callback)` but it doesn't work for me.

**Comment by Vaviloff** [comment]
> what the signature of the function ?

In fact, signature it this:
`page.evaluate(fn, callback, var1, var2, ...)`
