### ISSUE TITLE
Calling ph.exit() doesn't terminate spawned process

### ISSUE THREAD

**Issue by ryanone** [alexscheelmeyer/node-phantom#24]
Hi, has anyone else encountered this issue?  I spawn one or more child processes (ie. PhantomJS instances).  After opening up whatever web pages I need to open up, I naturally want to call exit().  However, this doesn't kill/terminate the child processes, and so I'm left with a bunch of orphans.

I've found what hopes to be a fix.  Inside of node-phantom.js, we have a proxy variable at the bottom, which is an object with an exit() method.  Right now, all it does is call request().  If we add a call to phantom.exit('SIGTERM'), that seems to do the trick.

I can send a pull request if you'd like.

Thanks!

**Comment by alexscheelmeyer** [comment]
Lets keep the discussion in the pull request.
