### ISSUE TITLE
--- DO NOT USE THIS LIBRARY ---

### ISSUE THREAD

**Issue by AndrewRayCode** [alexscheelmeyer/node-phantom#27]
this library is unmaintained, full of bugs and missing features. the codebase is currently unmanagable due to many conflicting pull requests. 

**Please join me in deleting your forks of this repository**

You should be using [phantom-proxy](https://github.com/sheebz/phantom-proxy), which is actively maintained and full featured.

There are several conflicting phantomjs libraries out there right now, and this one seems like it's ready to be put to bed.

**Comment by alexscheelmeyer** [comment]
Stop whining. We are talking very few lines of code here, if you have a problem fix it locally.

I am sorry that I have not been updating more often and I apprecriate the pull requests with new features - but remember that you are a developer and you should be able to understand and modify the libraries that you use, especially a small wrapper like this.

**Comment by AndrewRayCode** [comment]
I started to fix things locally, but you hadn't been accepting PRs for two months. as it's much nicer to tell a team to do npm install -g project rather than clone a fork of it, pull, and then install, I decided to move to an actively maintained one. I have contributed many patches to phantom-proxy now.
