### ISSUE TITLE
Please specify node-phantom's licence

### ISSUE THREAD

**Issue by giacecco** [alexscheelmeyer/node-phantom#3]
Hi alexscheelmeyer,
Would you mind specifying your licence of choice for node-phantom? Although I did not study your code I prefer your approach to the older [sgentle / phantomjs-node](https://github.com/sgentle/phantomjs-node), but I would also like to be sure of what your intentions are. At the moment you just write that it is "released to the public domain".

Thanks!

**Comment by alexscheelmeyer** [comment]
My intentions are to have as permissive a license as possible. Meaning you can do anything with the code and do not need to credit me or anything. By releasing it to the public domain I am trying to waive the copyright.

I am not a lawyer and do not appreciate reading long EULA's and policies. So I do not want to push such craziness on others. I realize that it might be easier for some if I pointed to a specific known license, but I am not interested in perpetuating this endless cycle of letting lawyers dictate how we give away stuff for free.

**Comment by giacecco** [comment]
Understood, thanks.
