### ISSUE TITLE
Crashes when specifying phantomjs parameters

### ISSUE THREAD

**Issue by eddiefletchernz** [alexscheelmeyer/node-phantom#37]
```
phantom.create(callback,{parameters:{'ignore-ssl-errors':'yes'}})
```

This will produce this error:

```
....\node_modules\node-phantom\node-phantom.js:24
                                args.push('--' + option + '=' + options.parameters[parm]);
                                                 ^
ReferenceError: option is not defined
    at spawnPhantom (....\node_modules\node-phantom\node-phantom.js:24:22)
    at Object.module.exports.create (....\node_modules\node-phantom\node-phantom.js:60:3)
```

To fix it, replace "option" with "parm" on line 24:

```
for(var parm in options.parameters) {
                args.push('--' + parm + '=' + options.parameters[parm]);
            }
```

**Comment by jsdw** [comment]
I bumped into this same problem. Hopefully it'll be fixed next update :)

**Comment by CrisFavero** [comment]
I just ran into this problem too... Though looking at the code it was corrected over a month ago , so i will assume that like me you are probably using npm  which for whatever reason is installing an older version and this is the real problem, change npm to load the git directly ad it will likely fix your problem too.

Note Dev's should update repo

**Comment by alexscheelmeyer** [comment]
This is fixed in latest npm version. Sorry for the delay.
