### ISSUE TITLE
WebPage.viewportSize parameter ignored?

### ISSUE THREAD

**Issue by giacecco** [alexscheelmeyer/node-phantom#4]
Hi alexscheelmeyer, 
I believe node-phantom is ignoring the viewportSize parameter of PhantomJS' WebPage object. When I set it and then open and render the page I get an image whose width is 400 pixels, that is PhantomJS' standard rather than what I specify.

I have also tried [sgentle/phantomjs-node](https://github.com/sgentle/phantomjs-node)'s syntax style doing something like: 

```
page.set('viewportSize', { width: 200, height: 400 });
```

but the set method does not exist.

Unless you plan to address this soon, I will likely have to drop node-phantom for sgentle/phantomjs-node, as simulating a given web browser width is absolutely necessary to me.

Thanks.

G.

**Comment by alexscheelmeyer** [comment]
Hi Gianfranco

That functionality was missing, sorry. I have made a quick update with get and set support. I wanted to get this update done quickly so you could continue your work, so it does not have extensive testing yet. This is a test-script that I have verified to work though :

``` javascript
phantom.create(function(error,ph){
    ph.createPage(function(err,page){
        page.get('viewportSize',function(err,value){
            console.log(value);
            page.set('viewportSize',{width:800,height:600},function(err){
                page.open('http://google.com',function(err,status){
                    page.render('google.png',function(err){
                        ph.exit();
                    });
                });
            });
        });
    });
}); 
```

Let me know if it works for you and thanks for reporting this.

**Comment by giacecco** [comment]
Fantastic! I've tested it already and it appears to be working nicely!

**Comment by alexscheelmeyer** [comment]
That is great to hear. I have reopened the issue to remind me to include some automated tests.

**Comment by hayesmaker** [comment]
this is horrible implementation, why can''t we set viewport in the normal phantom way?

**Comment by babbelnedd** [comment]
This isn't working anymore. How to do this yet?
