### ISSUE TITLE
node-phantom.js options.parameters

### ISSUE THREAD

**Issue by uittilla** [alexscheelmeyer/node-phantom#48]
When passing params into phantom.create it throws an error. Its a slight overlook but here it is. Sorry to all if its already been reported.

line 24 in node-phantom.js

for(var parm in options.parameters) {
-->      args.push('--' + option + '=' + options.parameters[parm]);
}

Works when i change it to 'parm'

for(var parm in options.parameters) {
     args.push('--' + parm + '=' + options.parameters[parm]);
}

Cheers

**Comment by cedmax** [comment]
it seems to be already fixed in the source, not pushed to npm though

**Comment by cedmax** [comment]
update: 

I solved adding to my package.json

```
"node-phantom": "git://github.com/alexscheelmeyer/node-phantom.git#7b82108a45ad22a3ca38f1383593e66d5369d574",
```

**Comment by uittilla** [comment]
Many thanks

Nice lib BTW :) very usefull

**Comment by alexscheelmeyer** [comment]
This is now pushed to npm so no reasons for workarounds. Sorry for the delay.
