### ISSUE TITLE
Null result on scraping new page after click 

### ISSUE THREAD

**Issue by alyraz** [alexscheelmeyer/node-phantom#51]
Hello, it's possible I am missing some very basic here but have been googling and overflowing for hours so figured I ask here too. 

I am successfully scraping data from the first page, but then I have to click on a link to the next page and repeat. Right now I can only get back a null result, but with no errors. The first result (availabilities) is working perfectly. I can't seem to find any good code examples of scraping-clicking-scraping with this module so I might just be making a silly mistake. Thanks in advance for any help!

``` javascript
page.includeJs('http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js', function(err) {
            page.evaluate(function() {
              var availabilities = [];
              $('#calendar tbody tr').each(function() {
                $(this).children().filter('.a').each(function(){
                  availabilities.push( $(this).children().attr('href') );
                });
              });
              return {
                availabilities: availabilities,
              };
            }, function(err,result) {
              console.log(result.availabilities.length);
            });
            page.evaluate(function(){
             var body = "";
             $('#nextWeek')[0].click(); //move to the next two weeks
             page.onLoadFinished = function(status){
              body += $('body').html();
             }
              return {
                body: body
              };
            }, function(err, result){
                console.log(result)
            });
        ph.exit();
        }); // page.includeJs
```

**Comment by alexscheelmeyer** [comment]
I guess you got it working?

If not I could try and reproduce at my end but I would need a more comprehensive example that at least shows which url you are trying to load.
