### ISSUE TITLE
createPage callback not fired in node v0.10

### ISSUE THREAD

**Issue by cedmax** [alexscheelmeyer/node-phantom#58]
I've noticed that using node 0.10 this code doesn't work

```
(function(){
    var phantom = require('node-phantom');

    phantom.create(function(e, ph){
        ph.createPage(function() {
            console.log("in");
        });
    });
})();
```

not sure what the issue is, but it works just fine with node 0.11 and <0.10

**Comment by skotchio** [comment]
I have the same one!

**Comment by accerqueira** [comment]
I had the same problem with node v0.10.8, upgraded to v0.10.12 and the problem is gone!

**Comment by skotchio** [comment]
Yes in a new nodejs version all works fine!

**Comment by alexscheelmeyer** [comment]
Weird. I am currently on 0.10.7 and does not see issues. Probably just a temporary fluke in node.

**Comment by jokeyrhyme** [comment]
I'm currently experiencing this with Node.JS v0.10.26 on OS X 10.9.3 (dev seed).

According to my `console.log` output, the callback for `phantom.create` is being called, with no error, but the callback for `ph.createPage` is not being called at all. I'm even really sure where to start diagnosing this.

**Comment by jokeyrhyme** [comment]
By the way, that's with the phantomjs@1.9.7-4 and node-phantom@0.2.5 packages.

Could this be related to #97 ?

**Comment by electerious** [comment]
Same problem when using node v0.10.28, phantomjs@1.9.7 and node-phantom@0.2.5 on OS X 10.9.

``` coffee

console.log 0

phantom.create (err, ph) ->

    console.log 1
    console.log err
    console.log ph

    ph.createPage (err, page) ->

        console.log 2
```

The output:

```
0
1
null
{ createPage: [Function],
  injectJs: [Function], …
```

The callback of ph.createPage never fires. No error…

**Comment by electerious** [comment]
#102 is responsible for this issue.

**Comment by zhouseahe** [comment]
@alexscheelmeyer  , It seems several people confused by  the version of socket.io . So , ah, I think you can test again  . If  Socket.io >=1.0.0 have no much promote for node-phantom , Set version to 0.9.17 should be considered . what if it's a bug of Socket.io . thanks for your work . thanks you can read my lines

**Comment by Ryan-YJL** [comment]
The latest version of node and socket.io are causing problems hanging with no response or an "Enoent" error. I'm using node locally for parsing/scraping data from the web so I can set the version as required. 

Using the info the commenters, I downgraded to node 0.10.7 and set node_modules/node-phantom/package.json to use 
<pre lang="javascript">
"dependencies": {
    "socket.io": "0.9.17"
  },
<code>
npm install and got it working again.
