### ISSUE TITLE
Access to page.settings or other way to change user agent? 

### ISSUE THREAD

**Issue by jfeldstein** [alexscheelmeyer/node-phantom#6]
I'm writing a script to pull my simple.com bank account using phantom to login and scrape the data, but need  to set a custom user agent. 

In native phantomjs, I'm doing this via: 

```
page.settings.userAgent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.4 (KHTML, like Gecko) Chrome/22.0.1229.64 Safari/537.4'
```

Is there an analogous command in `node-phantom`?

**Comment by jfeldstein** [comment]
I found an example of changing the `userAgent` in the tests, but now I'm missing how to set an `onLoadFinished` callback. I see it in the `testpagepushnotifications.js` test, but it isn't actually tested and isn't working in the same way as the others.

How should I be doing this?

**Comment by jfeldstein** [comment]
PS. I'm setting the onLoadFinished callback, but it's never getting called. I think maybe I'm misinterpreting the effects of https://github.com/alexscheelmeyer/node-phantom/commit/45014fd405108b1bcf7f22107667c5c98ef535a9

**Comment by nym** [comment]
I needed to do this as well, so I found the referenced test page:

https://github.com/alexscheelmeyer/node-phantom/blob/master/test/testpagesetget.js

Here's the snippet:

```
page.set('settings',{'userAgent':'node-phantom tester'},function(err){});
```

**Comment by nym** [comment]
In the end I did this to get it to work.

```
                    page.set('settings', {
                        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",
                        javascriptEnabled: true,
                        loadImages: true
                    });
```

**Comment by alexscheelmeyer** [comment]
Yes, the page.set function is the way to do it.

**Comment by reverie** [comment]
@alexscheelmeyer , the tests show use of .set('userAgent', ...), but it doesn't actually do anything. The tests pass, but the client doesn't use the passed-in user-agent. You have to use @nym 's solution, including the JS and images settings, to properly set the user agent.

**Comment by JohanDufau** [comment]
You need to specify `.userAgent` for the first argument of page.set function like this :

``` js
page.set('settings.userAgent', 'your new user agent string');
```
