### ISSUE TITLE
handling console.log in the browser

### ISSUE THREAD

**Issue by fschwiet** [alexscheelmeyer/node-phantom#60]
Is there a way to listen to the browser console with node-phantom?  It looks like phantom.js may output that information to the console, maybe node-phantom has an event for that?

**Comment by potmo** [comment]
there is. 
From the top of my head it's something like this:
page.onConsoleMessage = function(mess){}

same goes for onError

**Comment by fschwiet** [comment]
confirmed that onConsoleMessage and onError work as described.

**Comment by pvoisin** [comment]
Running my test with node+phantom doesn't seem to work properly (node 0.8.15, phantom 0.5.2) whilst running something like phantomjs test.js seems to work properly.

Do you need me to file an other issue or you would just re-open this one?
