### ISSUE TITLE
phantom.onError?

### ISSUE THREAD

**Issue by fschwiet** [alexscheelmeyer/node-phantom#61]
Is there a way to get error messages sent to phantom.onError?  onError is documented here: https://github.com/ariya/phantomjs/wiki/API-Reference-phantom?

**Comment by potmo** [comment]
Try:

``` javascript
page.onConsoleMessage = function(mess)
{
    console.log("PAGE: " + mess);
}
```

and

``` javascript
page.onError = function(err){
    console.error("ERRR: " + err);              
}
```

**Comment by fschwiet** [comment]
Thanks.  Though I can't verify this right now, I'll go ahead and close the issue.

**Comment by fschwiet** [comment]
I did eventually verify this works :)  thanks
