### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by benjamind** [alexscheelmeyer/node-phantom#70]
There's some good pull requests that have been sitting here for many months now.

I'm actually using this in a production project, and need the pull requests, I've resorted to making my own repository to apply the patches, but I would much prefer for another official release with pull requests included.

@alexscheelmeyer can you find the time to merge some of these and push a new version? Specifically issue #68 could really do with being merged as it causes random failures that are hard to debug.

If you don't have the time perhaps you could ask a couple of the people who've filed requests to be collaborators?

**Comment by alexscheelmeyer** [comment]
No it is not abandoned. But you are right in that I am pretty pressed for time. Actually I have some time right now and will look at the issue you mention right away.

**Comment by benjamind** [comment]
Fair enough thats great to hear!

Thanks!
